### ISSUE TITLE
DASWG: Leave Fold Angle in WICG for now and collaborate with CSS

### ISSUE THREAD

**Issue by tantek** [w3c/das-charter#102]
Per [DAS charter feedback](https://lists.w3.org/Archives/Public/public-new-work/2020Jun/0012.html): The Fold Angle specification should be incubated in the WICG before it becomes a working group deliverable. For Fold Angle, we'd also like to see closer collaboration and input from the CSS WG on the design.

Having said that, we would be comfortable with having WICG incubated specs being explicitly listed as charter work items that the working group could adopt at a future date. However, we'd like to see them listed in a manner similar to the [Web Apps WG Charter's section on WICG Specs](https://www.w3.org/2019/05/webapps-charter.html#wicgspecs) (i.e., separated out of the main deliverables list for the working group).

cc: [@dwsinger](https://github.com/dwsinger) [@pes10k](https://github.com/pes10k) [@marcoscaceres](https://github.com/marcoscaceres) [@torgo](https://github.com/torgo) [@dbaron](https://github.com/dbaron)

(Originally published at: https://tantek.com/2020/188/b5/das-fold-angle-wicg)

**Comment by torgo** [comment]
I would like to make a case that this work should not be consigned to WICG. The work is at a [good stage of development](https://diek.us/fold-angle/) - beyond many other work items in WICG. It makes much more sense for it to be worked on in a full working group which has already accepted it into its charter. While it's definitely true that some of the work would need to happen in CSS, I think it makes much more sense for the initial work to progress in DASWG than WICG and for that collaboration to happen between CSS WG and DASWG.

As a meta comment, WICG is a great place to incubate new ideas but in the TAG we are generally encouraging work to happen or to have a trajectory towards full working groups – this is something we encourage through our design review process. It's a little frustrating to see someone recommending that a spec move backwards from an already drafted WG charter to WICG, especially when many W3C member organisations have already made commitments to work in that working group.

**Comment by diekus-zz** [comment]
I completely agree with @torgo. I personally do not see this API elsewhere and I am convinced DASWG is the group to go to. I also think collaboration between DASWG and CSSWG is how I envision this working due to the support we want to provide from CSS to this new feature.

**Comment by anssiko** [comment]
I've discussed with @astearns (from Adobe, CSS WG co-chair) and he's happy with the proposed collaboration model between the DAS WG and CSS WG for this deliverable.

**Comment by xfq** [comment]
Not directly related to this issue, but we could perhaps add CSSWG to the [Coordination](https://w3c.github.io/dap-charter/DASCharter-2020.html#coordination) section to for the work on some [media features](https://drafts.csswg.org/mediaqueries-5/).

**Comment by xfq** [comment]
The Director [has approved](https://www.w3.org/2020/11/das-wg-charter.html) the Devices and Sensors Working Group charter, taking into consideration the input from an experiment conducted by the Advisory Board and the TAG. A liaison to the CSS working group has been added to the charter and the maturity of this specification has been clarified.

See https://lists.w3.org/Archives/Member/w3c-ac-members/2020OctDec/0034.html (member-only link) for the Director's decision.
