### ISSUE TITLE
DASWG: Drop Orientation Sensor in favor of existing APIs

### ISSUE THREAD

**Issue by tantek** [w3c/das-charter#104]
Per [DAS charter feedback](https://lists.w3.org/Archives/Public/public-new-work/2020Jun/0012.html): Where we already have an existing Web APIs, e.g., Orientation Sensor, we would prefer the working group cease work on those items and instead focus on evolving the existing specifications.

cc: [@dwsinger](https://github.com/dwsinger) [@pes10k](https://github.com/pes10k) [@marcoscaceres](https://github.com/marcoscaceres)

(Originally published at: https://tantek.com/2020/188/b7/das-drop-orientation-sensor)

**Comment by anssiko** [comment]
The Orientation Sensor specification differs from the "existing specifications" in the following ways:

- [x] defines new features [1] that address new use cases [2],
- [x] addresses significant interoperability issues e.g. around sensor fusion [3],
- [x] improves API ergonomics, makes the API consistent with other similar APIs and extensible [4], and
- [x] defines modern privacy and security protections to address known privacy and security threats, and a model that is extensible with additional mitigations [5]

The DAS WG is [commitment](https://www.w3.org/2020/05/proposed-das-wg-charter.html#scope) to **security and privacy focused** and **use case-driven** specification development and believes ceasing this work would be considered harmful.

[1] https://w3c.github.io/orientation-sensor/#intro
[2] https://w3c.github.io/motion-sensors/#usecases-and-requirements
[3] https://w3c.github.io/motion-sensors/#fusion-sensors
[4] https://w3c.github.io/sensors/#concepts
[5] https://w3c.github.io/sensors/#security-and-privacy

**Comment by xfq** [comment]
The Director [has approved](https://www.w3.org/2020/11/das-wg-charter.html) the Devices and Sensors Working Group charter, taking into consideration the input from an experiment conducted by the Advisory Board and the TAG and decided that a chartered Working Group was best suited to address the architecture concerns (new approach to existing APIs). These concerns will not be ignored but the discussion should be moved into the individual specification issue tracker where the concerns can be addressed.

Moreover, the Director recommended this document be republished as a Working Draft, with a Changes section.

See https://lists.w3.org/Archives/Member/w3c-ac-members/2020OctDec/0034.html (member-only link) for the Director's decision.
