### ISSUE TITLE
DASWG: Drop Network Information API because it is harmful to the web

### ISSUE THREAD

**Issue by tantek** [w3c/das-charter#105]
Per [DAS charter feedback](https://lists.w3.org/Archives/Public/public-new-work/2020Jun/0012.html): Mozilla has significant concerns about the inclusion of the Network Information API in the charter (as a specification to potentially adopt from the WICG) — Mozilla's public position is that this API is "harmful" to the Web as the information that it provides is unreliable and, at the same time, open to privacy abuses. As we have [stated publicly](https://mozilla.github.io/standards-positions/#netinfo), we believe it is "better that sites use methods that dynamically adapt to available bandwidth, as that is more accurate and likely to be applicable in the moment". Or, alternatively, use newer declarative solutions, such as "lazy loading" images and alike.

cc: [@dwsinger](https://github.com/dwsinger) [@pes10k](https://github.com/pes10k) [@marcoscaceres](https://github.com/marcoscaceres)

(Originally published at: https://tantek.com/2020/188/b8/das-drop-network-information-api)

**Comment by anssiko** [comment]
The group believes the following provision in the [proposed charter ](https://www.w3.org/2020/05/proposed-das-wg-charter.html#deliverables) alleviates the objector's concerns:
>Note: the group will determine in collaboration with the WICG whether the existing implementations of this API on mobile warrant restarting the standardization process

Please also note this text is unchanged from the [current charter](https://www.w3.org/2019/03/devices-sensors-wg-charter.html#deliverables).

The DAS WG is aware of the ongoing discussion in WICG to limit the scope of this specification [1]. Should implementers in WICG agree on such a subset, the DAS WG remains committed to help bring the agreed upon subset of functionality to the standards track.

The DAS WG is [commitment](https://www.w3.org/2020/05/proposed-das-wg-charter.html#scope) to **security and privacy focused** and **use case-driven** specification development and suggest the following clarification to the proposed charter to address the objector's concern (emphasis mine):

>Note: the group will determine in collaboration with the WICG whether the existing _use cases and_ implementations of this API on mobile warrant restarting the standardization process

[1] https://github.com/WICG/netinfo/issues/84

**Comment by xfq** [comment]
See also the discussions in TPAC:

* https://www.w3.org/2020/10/22-dap-minutes.html#t04
* https://www.w3.org/2020/10/23-dap-minutes.html#t05

**Comment by xfq** [comment]
The Director [has approved](https://www.w3.org/2020/11/das-wg-charter.html) the Devices and Sensors Working Group charter, taking into consideration the input from an experiment conducted by the Advisory Board and the TAG and decided that a chartered Working Group was best suited to address these concerns. These concerns will not be ignored but the discussion should be moved into the individual specification issue tracker where the concerns can be addressed.

Although the decision allows for keeping it in the scope of the charter, given the architectural concerns (like the first-hop connection may not be diagnostic) raised against the Network Info API, a conversation with the TAG and networking experts about at least its fundamental assumptions and approach, and that any intrinsic concerns be addressed in or before FPWD is recommended.

See https://lists.w3.org/Archives/Member/w3c-ac-members/2020OctDec/0034.html (member-only link) for the Director's decision.

**Comment by tomayac** [comment]
I have rebooted the Network Information API based on long-going discussions with @yoavweiss (who is currently still OoO) and would appreciate you all's feedback:

- Motivational doc: https://docs.google.com/document/d/1RDA23zSNdDuIcxZTX9Xo3zlD2fxf8dZg9-e0YaJQv0g/edit?usp=sharing
- Explainer: https://github.com/tomayac/netinfo/blob/relaunch/README.md
- Spec draft: https://ghcdn.rawgit.org/tomayac/netinfo/relaunch/index.html

**Comment by anssiko** [comment]
Huge thanks to @tomayac for addressing the [resolution from TPAC 2020](https://www.w3.org/2020/10/22-dap-minutes.html#r01). This substantial contribution helps inch this spec closer to WG adoption. DAS WG keeps close eye on this spec and will offer it a home depending on its ongoing progress and implementation experience.

**Comment by tomayac** [comment]
Thanks, Anssi! Good to have home and shelter :-) ! Now hoping for a lot of early feedback so I can get the proposal in a good shape so I can file for TAG review.

**Comment by marcoscaceres** [comment]
I'm feeling like we should maybe have a brainstorming sessions around different ways of addressing the netinfo use cases. The NetInfo API itself is quite polarizing, so if we could free ourselves from it entirely, while still addressing the use cases, that might be a better approach.
