### ISSUE TITLE
DASWG: Drop Generic Sensor API

### ISSUE THREAD

**Issue by annevk** [w3c/das-charter#106]
Although not explicitly mentioned https://lists.w3.org/Archives/Public/public-new-work/2020Jun/0012.html, Mozilla would like to request the work on the Generic Sensor API to stop as the privacy and security story is weak at best and there is only a single implementation.

We would be interested in pursuing the underlying use cases and finding alternative ways of addressing them in ways that do not give websites direct access to sensors.

Thank you for your consideration and apologies for the late notice.

**Comment by hober** [comment]
> We would be interested in pursuing the underlying use cases and finding alternative ways of addressing them in ways that do give websites direct access to sensors.

Is this sentence missing a "not" in it?

**Comment by annevk** [comment]
Thanks, addressed.

**Comment by xfq** [comment]
The Director [has approved](https://www.w3.org/2020/11/das-wg-charter.html) the Devices and Sensors Working Group charter, taking into consideration the input from an experiment conducted by the Advisory Board and the TAG and decided that a chartered Working Group was best suited to address these concerns. These concerns will not be ignored but the discussion should be moved into the individual specification issue tracker where the concerns can be addressed.

See https://lists.w3.org/Archives/Member/w3c-ac-members/2020OctDec/0034.html (member-only link) for the Director's decision.
