### ISSUE TITLE
Idle Detection API

### ISSUE THREAD

**Issue by xfq** [w3c/das-charter#110]
Making a note here that https://wicg.github.io/idle-detection/ might advance to DAS WG in the future.

See also https://github.com/WICG/idle-detection/issues/40

**Comment by xfq** [comment]
Related info:

* [Chrome Platform Status](https://www.chromestatus.com/feature/4590256452009984)
* [Chromium Intent to Ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/ZmHHfrR_jak?pli=1)
* [Mozilla position](https://github.com/mozilla/standards-positions/issues/453)
* [WebKit position](https://lists.webkit.org/pipermail/webkit-dev/2020-October/031558.html)

**Comment by anssiko** [comment]
Addressed by https://www.w3.org/2022/11/das-wg-charter.html
