### ISSUE TITLE
Compute Pressure API -> System Pressure

### ISSUE THREAD

**Issue by oyiptong** [w3c/das-charter#111]
Making a note here for https://github.com/oyiptong/compute-pressure to be part of the DAS WG.

**Comment by anssiko** [comment]
Thanks @oyiptong!

@xfq please take this into considerations for the next charter revision.

**Comment by xfq** [comment]
Link to the TAG review: https://github.com/w3ctag/design-reviews/issues/621

**Comment by xfq** [comment]
Because this is only a preliminary proposal, can we consider whether to transfer it to DAS WG after asking the opinions of other browser vendors and having a draft spec?

**Comment by anssiko** [comment]
That is definitely a good suggestion, but I feel it could also happen in parallel. Often it takes time for browser vendors to form an informed opinion.

I feel this API should be considered a Tentative Deliverable and its adoption as a Normative Specification should depend on its incubation progress that includes signals from implementers (plural).

One way to go about this would be to clarify those specific expectations in the charter for this API similarly to the Network Information API. Proposal:

>Note: the group will determine in collaboration with implementers whether there's adequate support to advance this proposal to standardization from incubation

This assuming the technical scope of the proposal can be articulated in enough detail at the time the charter is reviewed by the AC. Per my assessment of the explainer it has enough detail for such an evaluation to take place.

As for the draft specification, @kenchris I believe is helping @oyiptong formalize the specification and we should see some output of that effort soon.

**Comment by xfq** [comment]
OK. Added in https://github.com/w3c/dap-charter/commit/482168e19a40173648ea0fed5e70fc9d8138529c

**Comment by anssiko** [comment]
FTR: draft spec: https://wicg.github.io/compute-pressure/

**Comment by anssiko** [comment]
We now have substantial implementation experience for the first version of the Compute Pressure API, and further work is under way. We have also received new feedback from users and web developers with suggestions for new use cases. These use cases have been documented in the Compute Pressure API GH repository and labeled with "[v2](https://github.com/WICG/compute-pressure/issues?q=is%3Aissue+is%3Aopen+label%3AV2)".

Given this new information and interest, I'm proposing we consider adjusting the description of this API in the charter to be inclusive of these new use cases.

To start the discussion, here's my first stab against the [latest charter version](https://w3c.github.io/dap-charter/DASCharter-2021.html) (still in [Council review](https://www.w3.org/Member/wiki/DirectorFOdashboard#Devices_and_Sensors_proposed_charter)) that I hope is not too abstract:
```diff
-Compute Pressure
+System Pressure

-An API that conveys the utilization of CPU resources on the user's device
+An API that conveys information on how the hardware platform is operating
+in relation to its normal operating bounds.
```
I'm not a big fan of changing the spec title, but in this case it feels "System Pressure" would be more accurate and future-proof name, also symmetrical with the WG's another deliverable, System Wake Lock API.

@kenchris, we should discuss these new use cases and this proposal at the [WG's TPAC meeting](https://github.com/w3c/devicesensors-wg/issues/56) as part of our charter scope 2023-2024 discussion.

**Comment by anssiko** [comment]
Addressed by https://www.w3.org/2022/11/das-wg-charter.html
