### ISSUE TITLE
Joint deliverables with WebApps WG

### ISSUE THREAD

**Issue by anssiko** [w3c/das-charter#123]
There is a proposal to broaden the scope of joint deliverables between the DAS WG and WebApps WG. For the list of proposed joint deliverables, see: https://github.com/w3c/webappswg/issues/90

Rationale: This would allow members who are not participants of the DAS WG but are participants of the WebApps WG to contribute substantively to the DAS WG specifications identified as joint deliverables. For the current DAS WG participants this proposed change would be largely transparent. Some extra cross-group coordination would be needed for meetings and certain publications, but the day-to-day work would proceed as usual.

Concrete actions required:

- Reach agreement on the joint deliverables between the WGs. This can be a relatively quick exercise if both the WGs work together in good faith as expected. The chairs and staff would facilitate this process.
- Update both the DAS WG and WebApps WG charters to identify the joint deliverables. These changes require an [AC review](https://www.w3.org/2021/Process-20211102/#CharterReview) that is a costly step. This would similarly be handled by the chairs with assistance from the staff.

If we reach agreement, to ensure timely progress, we may want to consider an off-cycle refresh to both the charters. The proposed DAS WG charter with Contact Picker API as the joint deliverable is expected to be operational "soon" awaiting W3C Council recommendation and there's a WIP PR https://github.com/w3c/das-charter/pull/122 on top of it to provide a branch where to incorporate changes for possible additional joint deliverables in the next off-cycle charter update. The [WebApps WG charter](https://www.w3.org/2022/04/webapps-wg-charter.html) is due for its scheduled update in Q2 2024, which seems too long time to wait. This further emphasizes the need for an off-cycle refresh.

**Comment by reillyeon** [comment]
I have no objection to this as it enables progress.

Separately I would like to work on a solution which would enable any of the existing WebApps WG members interested in contributing to specifications under the DAS WG charter to join, as I feel that the WebApps WG has the same problem as the DAS WG with a rather broad charter and joint deliverables only make that worse.

**Comment by anssiko** [comment]
New draft PR for developing the joint deliverables proposal: #124

**Comment by anssiko** [comment]
Closed a bit too early. Re-opening.

**Comment by anssiko** [comment]
Here's the PR for developing the joint deliverables proposal: https://github.com/w3c/das-charter/pull/126

Sorry about the noise. I first deployed the baseline draft to keep us focused on joint deliverables related changes only.

**Comment by anssiko** [comment]
We observe intensifying interest from the WebApps WG toward the Screen Wake Lock API developed in the DAS WG. To that end, I updated PR #126 with a proposal to add the Screen Wake Lock API as a joint deliverable.

In order to proceed in a timely manner with this effort, we would ask everyone to share their feedback as soon as possible, latest EOY. We have received only support signals to date. Thank you for your support!

See also: [HTML diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2022%2F11%2Fdas-wg-charter.html&doc2=https%3A%2F%2Fcdn.statically.io%2Fgh%2Fw3c%2Fdas-charter%2Fjoint-deliverables%2Fdas-wg-charter.html) between the current DAS WG charter and PR #126.

Edit: update HTML diff link.

**Comment by rakuco** [comment]
> I have no objection to this as it enables progress.

Also +1 here, especially from a Screen Wake Lock API perspective.

**Comment by anssiko** [comment]
After extensive discussions with various parties, I'm pleased to share we're making progress with our joint deliverables proposal. The latest proposal is available for your review at:

https://w3c.github.io/das-charter/das-wg-charter.html ([diff to current](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fwww.w3.org%2F2022%2F11%2Fdas-wg-charter.html&doc2=https%3A%2F%2Fw3c.github.io%2Fdas-charter%2Fdas-wg-charter.html))

Thanks to all the reviewers who have carefully scrutinized this proposal from various perspectives. This has been a long journey. Once operational, this will further accelerate the adoption of the WG's device-centric deliverables.

There's one more thing, however. We expect our joint work mode to be clarified in this charter before we bring this forward because the Process Document does not currently define or recognise the joint deliverable concept at all and we depend on it. To not block on the Process Document missing this important definition, we plan to address this by incorporating the missing definition and its interactions with the applicable parts of the Process Document in the affected charter documents directly. And later, contribute these changes to the Process Document to ensure other WGs who may wish to adopt a similar joint work mode can refer to the canonical definition in their charter documents.

Thank you for your patience as we work out the important remaining details with the experts.

**Comment by plehegar** [comment]
Thank you for the update. cc @marcoscaceres

**Comment by plehegar** [comment]
@anssiko any update on this front?

**Comment by reillyeon** [comment]
> @anssiko any update on this front?

I believe he is still on vacation which means he didn't have time to get to this before he left.

**Comment by plehegar** [comment]
@anssiko any update on this front?

**Comment by anssiko** [comment]
@plehegar this is slated for discussion in https://github.com/w3c/devicesensors-wg/issues/66

**Comment by himorin** [comment]
(note) had discussed during TPAC DAS meeting, agreed as
https://github.com/w3c/w3process/issues/754#issuecomment-1719014704

**Comment by plehegar** [comment]
Can this issue be closed at this point?

**Comment by reillyeon** [comment]
Assuming we don't want to wait until the new charters are adopted I think this and https://github.com/w3c/webappswg/issues/90 can be closed.

**Comment by anssiko** [comment]
Addressed by [a proposed recharter](https://www.w3.org/2023/11/proposed-wg-das.html) now [under AC review](https://lists.w3.org/Archives/Member/w3c-ac-members/2023OctDec/0032.html) (Member-only) until 9 December 2023.

Thank you for your contributions @plehegar @himorin. We wouldn't have gotten here without your dedication and hard work. I want to extend my thank you to various stakeholders of the W3C community who have provided support and guidance on this long journey.
