### ISSUE TITLE
unclear requirement for implementations

### ISSUE THREAD

**Issue by mwichmann** [w3c/das-charter#20]
The following line comes out a bit unclear:

_To advance to Proposed Recommendation, each specification is expected to have two independent implementations of all features defined in the specification, including implementation on a constrained device (e.g. mobile phone, TV)._

Is this to be interpreted as two implementations, which must include a constrianed-device implementation? or two implementations,  which may include a constrained-device implementation.  Would two constrained-device implementations and zero mainstream browser implementations still count?

Propose we clarify.

**Comment by dontcallmedom** [comment]
I think the intent was the first, i.e. "two implementations, one of which on a constrained device"; and I don't think we ever tried to answer your last question. Also, I'm not sure calling a mobile phone a constrained device still matches the reality.

I guess I think the best approach would be to remove the "constrained device" requirement; I don't think it has mattered much in practice. Will propose a PR to that effect.
