### ISSUE TITLE
Integrate Web Bluetooth?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/das-charter#28]
There has been discussions during TPAC 2016 to bring the Web Bluetooth work to the formal standardization track as part of the DAS Working Group.

**Comment by dontcallmedom** [comment]
feedback from CG is that until there are implementation intents beyond Chromium, standardization would be premature

**Comment by anssiko** [comment]
For the record, a public support statement from the Bluetooth Special Interest Group (SIG) Developer Relations:

>The Bluetooth Special Interest Group (SIG) Developer Relations team would like to express their support for Web Bluetooth. We'd very much like to see it implemented in all browsers and adopted as a formal W3C standard. We're open to ideas as to how we may be able to help make that happen.

https://lists.w3.org/Archives/Public/public-web-bluetooth/2017Oct/0000.html

**Comment by anssiko** [comment]
@dontcallmedom, I will reopen this issue as a reminder to revisit at TPAC. Could be discussed e.g. in https://www.w3.org/wiki/TPAC/2017/SessionIdeas#Device_APIs_session

**Comment by koalie** [comment]
FYI https://twitter.com/w3c/status/920255864526778368

**Comment by anssiko** [comment]
Feedback from Device APIs breakout at TPAC seemed to suggest this API should not yet advance to the standards track, see: https://www.w3.org/2017/11/08-device-api-minutes.html

If you feel otherwise, please let us know in this issue.

**Comment by anssiko** [comment]
It seems wider implementation feedback would be preferred to advance this specification to standards track at this time.
