### ISSUE TITLE
Integrate WebNFC

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/das-charter#29]
similar to #28

**Comment by anssiko** [comment]
It seems wider implementation feedback would be preferred to advance this specification to standards track at this time.

**Comment by anssiko** [comment]
Now that we're preparing the DAS WG 2020-22 charter, we should revisit where we stand in terms of Web NFC implementation feedback in the year 2020.

Currently Chrome Origin Trial is in progress, which should provide us developer feedback:
https://developers.chrome.com/origintrials/#/view_trial/236438980436951041

In addition to the spec https://w3c.github.io/web-nfc/, there's also an informative article geared toward developers at https://web.dev/nfc/ that can be helpful.

**Comment by anssiko** [comment]
Feedback from STMicroelectronics: https://lists.w3.org/Archives/Public/public-web-nfc/2020Mar/0000.html

**Comment by anssiko** [comment]
No strong reactions for or against, we're leaning toward keeping the Web NFC in its own incubator.

**Comment by xfq** [comment]
Closing.
