### ISSUE TITLE
Restart work on DeviceOrientation Event API

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/das-charter#31]
The Geolocation Working Group's charter expired before they were able to complete the standardization work on [the DeviceOrientation Event](https://www.w3.org/TR/orientation-event/) spec.

Should this group take it over and finish it, given its work on the Generic Sensor API?

**Comment by anssiko** [comment]
I'd support DAS WG taking over the maintenance of the DeviceOrientation Event spec. Areas that could be improved in the spec include e.g. security and privacy considerations. Much of the learnings from the Generic Sensor API could be applied to this spec to fix ambiguities and make it better match the deployed implementations.
