### ISSUE TITLE
Environmental sensors

### ISSUE THREAD

**Issue by kenchris** [w3c/das-charter#33]
Environmental sensors are not common on laptops and phones, but could become pretty common in IoT and thus accessible via Web Bluetooth and the like.

The sensors themselves are probably quite easy to standardize as they expose data quite simple (no complex matrices, quaternions etc), but if we standardize these we will probably end up with things exposed the same way, and there is interest at least in the JS Runtime for Zephyr to follow such specs.

**Comment by dontcallmedom** [comment]
my hunch is that since there are quite a few hypotheses between having these APIs and having them implemented in browsers, my impression is that this would better started in a CG (e.g. [WICG](https://www.w3.org/community/wicg/) or a dedicated one) rather than directly in DAS.

**Comment by anssiko** [comment]
I think we have a resolution that everyone is happy with, closing this issue.
