### ISSUE TITLE
Any new sensor API?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/das-charter#4]
We had early draft of Ambient Temperature Events, Ambient Humidity Events, Atmospheric Pressure Events — assuming progress on the sensor API pattern, do we want to add this to our charter?

**Comment by anssiko** [comment]
Depending on whether there will be an agreement (https://lists.w3.org/Archives/Public/public-device-apis/2015Jul/0002.html) on migrating the Device Orientation into this group, we should naturally add that one since it is likely one of the most widely supported sensors out there.

The other sensors that are now considered exploratory work did not advance in the past due to the fact such sensors were not readily available in shipping devices, and thus interop was impossible. I'm wondering has that situation changed since couple of years? If so, then including them sounds reasonable. Any public data on what type of sensors are currently shipping in mainstream devices?

**Comment by wayneca** [comment]
In order to provide time to discuss a possible transfer after the charter was approved, charter could add to the sensor section:

[[
Acceleration API, Orientation API, Compass Bearing API

APIs providing device orientation, acceleration and compass bearing.  The DAP WG may adopt the Device Orientation API from the Geolocation WG at the request of that group, or could work on new APIs for acceleration, orientation and com[ass bearing using the new Generic Sensor API Pattern.
]]

**Comment by dontcallmedom** [comment]
@anssiko sources of data includes the [sensor APIs that Android ships with](http://developer.android.com/guide/topics/sensors/sensors_overview.html), including thermometer, barometer (which was added to the iPhone 6 from what I can see), magnetometer, humidity.

Another way to look at this is to look at the [list of cordova plugins](http://plugins.cordova.io/#/viewAll) and their download rates; I haven't gotten through the full list, but at least glancing through the top of the list, bluetooth and nfc seems in higher demand than others.

**Comment by dontcallmedom** [comment]
There has been agreement on the 2015-09-03 call to add a new generic-sensor-based device orientation API should be added to our future charter.

**Comment by anssiko** [comment]
Blast from the past.

We should reassess whether there are new sensor types (see [current types](https://www.w3.org/das/roadmap)) that are widely available in mainstream devices and have good use cases for the web that'd warrant starting standardization.

Just to give an example, the new class of dual-screen devices have a hinge in between and there's a sensor monitoring the angle of that hinge.

Related https://github.com/w3c/dap-charter/issues/33

**Comment by anssiko** [comment]
An idea on how the fold angle could be exposed via the Generic Sensor API:

https://github.com/SamsungInternet/Explainers/blob/master/Foldables/FoldState.md#angle-sensor-based-on-genericsensor-api

The authors @diekus and @kenchris seem to think the CSS media queries is the primary conduit, and the API could possibly be complementary surface. If so, we might consider inclusion into the DAS WG especially if we get positive reactions from implementers.

**Comment by tomayac** [comment]
For some background, the [hinge angle sensor](https://developer.android.com/reference/android/hardware/SensorEvent#sensor.type_hinge_angle-:) as described in the Android documentation.

**Comment by anssiko** [comment]
@tomayac:

>For some background, the hinge angle sensor as described in the Android documentation.

Fold Angle Sensor is added to the [draft charter proposal](https://w3c.github.io/dap-charter/DASCharter-2020.html).

> Barometer altitude (if the device has barometer) https://github.com/w3c/geolocation-sensor/issues/43#issuecomment-604911855

Here's how I unpack this, clarifications welcome:

Using GPS the method to measure altitude is called [trilateration](https://en.wikipedia.org/wiki/True_range_multilateration). This method has restrictions as outlined in the article. To get more precise altitude readings, some (or most modern mobile?) devices include [barometric altimeter](https://en.wikipedia.org/wiki/Altimeter) that measures the atmospheric pressure.

I think the proposal is to allow web developers to request "high precision altitude". This could be addressed by allowing developers to pass a flag upon instantiation of the GeolocationSensor, for example (note: this approach has caused interop issues in the past, see PositionOptions.enableHighAccuracy in Geolocation API). This would be already in scope, no changes required in the charter to pick up this work.

If, OTOH, there are reasonably mainstream use cases for requesting altitude _alone_ without lat/long, it'd make sense to split that feature into a separate sensor type to enable better privacy protections (users could grant access to altitude alone, and not lat/long). Also we need to understand  implementability (i.e. do platforms allow requesting just altitude), initial assessment https://github.com/w3c/geolocation-sensor/issues/43#issuecomment-604911855 suggests some platforms do expose this sensor type separately.

cc @karianpour

**Comment by tomayac** [comment]
> If, OTOH, there are reasonably mainstream use cases for requesting altitude alone without lat/long, it'd make sense to split that feature into a separate sensor type to enable better privacy protections

One use case I could come up with is a hiker or climber who wants to know the altitude difference that they climbed.

**Comment by anssiko** [comment]
>One use case I could come up with is a hiker or climber who wants to know the altitude difference that they climbed.

Are we aware of native apps like that? That would be one signal that'd help make a case this feature would be in demand and has real-world use cases.

**Comment by tomayac** [comment]
> Are we aware of native apps like that?

There are many altimeter kind of apps in the [Play Store](https://play.google.com/store/search?q=altitude&c=apps) and the [App Store](https://apps.apple.com/us/app/travel-altimeter-elevation/id486556174#see-all/customers-also-bought-apps).

**Comment by anssiko** [comment]
[Proposal](https://lists.w3.org/Archives/Public/public-device-apis/2020Apr/0003.html):

>No changes are needed to the proposed charter in order for the DAS WG to consider barometric altimeter a new location information source in the context of the Geolocation Sensor.
