### ISSUE TITLE
Network Information API

### ISSUE THREAD

**Issue by anssiko** [w3c/das-charter#40]
@dontcallmedom, do we need to clarify the relationship of https://www.w3.org/TR/netinfo-api/ currently linked to from the charter with https://wicg.github.io/netinfo/ actively being incubated in WICG?

**Comment by dontcallmedom** [comment]
here are the options I see:
* we add a link from the description in the charter to the WICG incubated version (leaving open the option to bring it to DAS if and when it is deemed ready)
* we remove Net Info from our charter
* we find out from the ongoing incubation of netinfo in WICG whether they see value in standardizing a subset of what they have (and whether that's DAS business or WebPerf, or …)

but yeah, clarification would be good :)
