### ISSUE TITLE
Adopt Web Share API?

### ISSUE THREAD

**Issue by anssiko** [w3c/das-charter#57]
It seems the [Web Share API][1] is ready to graduate from WICG to the Standards Track, see https://github.com/WICG/web-share/pull/54#issuecomment-347432513

I suggest we consider adopting the spec under the [new Devices and Sensors WG's Charter][2] (earlier Device APIs WG). Some observations:
- Timing would be quite good, since we're expecting the new charter to be in production ~March-April 2018.
- The spec would fit in the group's broader scope with no or minimal adjustments.
- The group has done related [Web Intents][3] work earlier (via Web Intents TF).

WDYT @xfq @dontcallmedom @samuelweiler

FYI @mgiuca @marcoscaceres 

[1]: https://wicg.github.io/web-share/
[2]: https://w3c.github.io/dap-charter/DeviceAPICharter.html
[3]: https://www.w3.org/TR/2013/NOTE-web-intents-20130523/

**Comment by xfq** [comment]
What's the status of Web Share Target API? Is it also ready to graduate from WICG?

**Comment by mgiuca** [comment]
@xfq I would say no for Web Share Target. We haven't had a TAG review yet (I'm working on a few changes first) and we've just started experimenting in Chrome.

Thanks for recommending this @anssiko. I don't have an opinion about which WG is suitable so I will leave others to comment.

**Comment by anssiko** [comment]
The plan is to get Web Share API adopted by the WPWG, see https://github.com/w3c/dap-charter/pull/58#issuecomment-352348490
