### ISSUE TITLE
is Web Bluetooth something DAP can/should adopt?

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/das-charter#6]
The [Web Bluetooth CG](https://www.w3.org/community/web-bluetooth/) is doing good work on their Bluetooth API; should we approach them to see if they're interested in standardization in DAP?

**Comment by carybran** [comment]
I think this is a good idea - the WG is currently focused on Bluetooth Smart (Low Energy) and not classic

**Comment by dontcallmedom** [comment]
The Web Bluetooth CG indicated they'd rather do it in the Web Platforms WG, so closing this issue.
