### ISSUE TITLE
Add the remaining deliverables to the timeline?

### ISSUE THREAD

**Issue by xfq** [w3c/das-charter#69]
In the AC review, @lvdbrink pointed out that not all the deliverables in 3.1 are present in the timeline
in 3.4. @anssiko, can we add the timeline for the remaining specs?

**Comment by samuelweiler** [comment]
Fixed with: 
https://github.com/w3c/dap-charter/commit/e1c4cbae35efbb954d0773d81b88742846131980#diff-052d0ffe1d4875c46aad73296a566b78

(Not yet merged into main branch)
