### ISSUE TITLE
Success criteria - already released APIs

### ISSUE THREAD

**Issue by svgeesus** [w3c/das-charter#82]
> APIs that cannot be demonstrated to be implementable securely within the default browser context will not be released.

APIs that have already released but are then demonstrated to not be implementable securely - should they be rescinded or moved back to Working Draft?

**Comment by anssiko** [comment]
I think that needs to be evaluated on a per spec basis in consultation with implementers should such an event occur.

W3C Process does prescribe the considerations for rescinding vs return to WD, which seems adequate.

**Comment by svgeesus** [comment]
Sounds good, thanks!
