### ISSUE TITLE
Goals and Scope editorial

### ISSUE THREAD

**Issue by anssiko** [w3c/das-charter#83]
Need editorial revision. Some text inherited from the past charters that had a broader scope.

**Comment by reillyeon** [comment]
The scope of device types seems broader than necessary,

> Devices in this context include desktop computers, laptop computers, mobile Internet devices (MIDs), cellular phones, TVs, cameras and other connected devices.

We could simplify this to "desktop and mobile computing devices" or similar.

**Comment by ellisonak** [comment]
I am glad someone is looking into this. My device is attached to this network without my consent. I am unable to view anything “live” my entire device is streamed. I have to follow Instagram just to see any post. This has been going on for years, no one has been able to help me discover what is going on. I am also unable to use WiFi anywhere. My webpages are pdf versions that someone has altered. Any information you can give me would be appreciated.

**Comment by xfq** [comment]
Fixed in #84.
