### ISSUE TITLE
move test-as-you-commit text?

### ISSUE THREAD

**Issue by samuelweiler** [w3c/das-charter#88]
The test as you commit text in section 2 seems partially redundant with the success criteria text is section 4.  Maybe move it to section 4?  (e.g. test-as-you-commit at CR; two implementations for PR)

I like the use of the blockquote rather than just repeating boilerplate - that's clever.  Please explain the origin of the blockquote in text - not just in the text of the URL.  Say it's W3C published testing policy.  Make the URL into a link!  Consider dropping the last sentence from the block quote, since that special case doesn't add much value in this charter (though we know it applies).

**Comment by samuelweiler** [comment]
It looks like the text was moved but the origin wasn't explained for a working link added.

**Comment by samuelweiler** [comment]
Looking further, the text was moved into "coordination", which makes no sense to me.  I was suggesting it be merged into the success criteria text which is section 3.  Not sure if the section numbering changed or I made a mistake above.

**Comment by xfq** [comment]
There is already a link to the page (i.e., the "test as you commit" text), and I'm not sure how to make the `cite` attribute of `blockquote` a link.

**Comment by xfq** [comment]
@samuelweiler Would you please confirm whether https://github.com/w3c/dap-charter/pull/92 is good enough?

**Comment by xfq** [comment]
Hearing no reply, I have just merged the PR.
