### ISSUE TITLE
Contact Picker API

### ISSUE THREAD

**Issue by anssiko** [w3c/das-charter#97]
Making a note here that https://wicg.github.io/contact-api/spec/ might advance to DAS WG in the future.

The group had [Contacts API](https://www.w3.org/TR/contacts-api/) in its charter 2009-2016, and the current Contact Picker API proposal could be characterized as a web-friendly subset of that API.

@reillyeon @marcoscaceres

**Comment by reillyeon** [comment]
I recently got an update that the Contact Picker API is being implemented in WebKit:

- https://twitter.com/tomayac/status/1362671289945755648
- https://github.com/WebKit/WebKit/tree/main/Source/WebCore/Modules/contact-picker

The group should reconsider adopting this specification from the WICG.

**Comment by marcoscaceres** [comment]
That's exciting to see! Yeah, the group should pick this up then.

**Comment by reillyeon** [comment]
Given this agreement what are the next steps? As I understand it adopting this API requires rechartering since it wasn't listed as a potential deliverable like Fold Angle was.

CC @xfq

**Comment by anssiko** [comment]
Per https://www.w3.org/2020/11/das-wg-charter.html#add-new we prepare an updated Charter that differs only in deliverables.

Also @plehegar should be able to assist.

**Comment by xfq** [comment]
> I recently got an update that the Contact Picker API is being implemented in WebKit:

Are there other browsers that have implemented, are implementing, or plan to implement this spec?

**Comment by xfq** [comment]
> Given this agreement what are the next steps? As I understand it adopting this API requires rechartering since it wasn't listed as a potential deliverable like Fold Angle was.

The next step is to go through the rechartering process (add it to the draft charter, ask for horizontal/management/AC review etc.). We can also organize a meeting before that to see if the WG has any ideas or suggestions.

**Comment by marcoscaceres** [comment]
> Are there other browsers that have implemented, are implementing, or plan to implement this spec?

I poked the Mozilla folks about it to see if they might consider it "worth prototyping". 
https://github.com/mozilla/standards-positions/issues/153#issuecomment-796422900

**Comment by xfq** [comment]
The Devices and Sensors Working Group just discussed Contact Picker API, and agreed to start the process to add Contact Picker API to the DAS WG Charter: https://www.w3.org/2021/04/06-dap-minutes.html#t01

**Comment by xfq** [comment]
Per discussions in https://github.com/w3c/strategy/issues/267 , we will make the Contacts Picker API a joint deliverable between WebApps and DAS.

**Comment by anssiko** [comment]
Addressed by https://www.w3.org/2022/11/das-wg-charter.html
