### ISSUE TITLE
DASWG: Drop Proximity sensor API for privacy and lack of implementer support

### ISSUE THREAD

**Issue by tantek** [w3c/das-charter#99]
Per [DAS charter feedback](https://lists.w3.org/Archives/Public/public-new-work/2020Jun/0012.html): On the the grounds of privacy, and given a lack of implementer support, we would like the Devices and Sensors Working Group to cease work on the Proximity sensor API and see it published as a Working Group Note instead.

cc: [@dwsinger](https://github.com/dwsinger) [@pes10k](https://github.com/pes10k) [@marcoscaceres](https://github.com/marcoscaceres)

(Originally published at: https://tantek.com/2020/188/b2/das-drop-proximity-sensor-api)

**Comment by anssiko** [comment]
All privacy issues brought up to the group's attention have been documented [1] and reviewed with privacy experts [2] with additional mitigations specified [1] on top of the mitigations inherited from the Generic Sensor API [3]. The implementation of these mitigations is work in progress alongside user studies to understand requirements of real-world use cases in terms of accuracy and sampling frequency.

The latest version of the Proximity Sensor API has implementer support [4] with shipping decision awaiting the above-mentioned work items to conclude satisfactorily. Multiple experimental implementations of the earlier version of the API [5] informed the development of the additional mitigations in place in the latest version of the API.

The DAS WG is [commitment](https://www.w3.org/2020/05/proposed-das-wg-charter.html#scope) to **security and privacy focused** and **use case-driven** specification development and believes ceasing this work would be considered harmful.

[1] https://w3c.github.io/proximity/#security-and-privacy
[2] https://github.com/w3c/proximity/issues/17
[3] https://w3c.github.io/sensors/#mitigation-strategies
[4] https://crbug.com/897317
[5] https://caniuse.com/#feat=proximity

**Comment by xfq** [comment]
The Director [has approved](https://www.w3.org/2020/11/das-wg-charter.html) the Devices and Sensors Working Group charter, and took into consideration the input from an experiment conducted by the Advisory Board and the TAG and decided that a chartered Working Group was best suited to address these concerns. These concerns will not be ignored but the discussion should be moved into the individual specification issue tracker where the concerns can be addressed.

Moreover, the Director recommended this document be republished as a Working Draft, with a Changes section.

See https://lists.w3.org/Archives/Member/w3c-ac-members/2020OctDec/0034.html (member-only link) for the Director's decision.
